name: lerobot
dependencies:
  - python=3.8.16
  - pytorch::pytorch=1.13.1
  - pytorch::torchvision=0.14.1
  - nvidia::cudatoolkit=11.7
  - anaconda::pip
  - pip:
    - cython==0.29.33
    - mujoco==2.3.2
    - mujoco-py==2.1.2.14
    - termcolor
    - omegaconf
    - gym==0.21.0
    - dm-env==1.6
    - pandas
    - wandb
    - moviepy
    - imageio
    - gdown
    # - -e benchmarks/d4rl
    # TODO: verify this works
    - git+https://github.com/nicklashansen/simxarm.git@main#egg=simxarm
