link0:
  origin:
    x: -0.0009483362816297526
    y: 0.0001580207020448382
    z: 0.03076860287587199
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 1.1432284943239561
  inertia:
    xx: 0.001128
    xy: -4.0e-06
    xz: -3.3e-05
    yy: 0.000962
    yz: -7.0e-06
    zz: 0.00147

link1:
  origin:
    x: 0.0011467657911800769
    y: 3.319987657026362e-05
    z: 0.05395284380736254
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 1.1416684646202298
  inertia:
    xx: 0.001567
    xy: -1.0e-06
    xz: -2.9e-05
    yy: 0.001273
    yz: 1e-06
    zz: 0.001016

link2:
  origin:
    x: 0.00839629182351943
    y: -2.0145102027597523e-08
    z: 0.03256649300522363
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 0.2775092746011571
  inertia:
    xx: 0.000359
    xy: 1e-06
    xz: -0.000109
    yy: 0.000376
    yz: 1e-06
    zz: 0.000232

link3:
  origin:
    x: -0.002104752099628911
    y: 0.0005549085042607548
    z: 0.09047470545721961
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 1.073863338202347
  inertia:
    xx: 0.004372
    xy: 1e-06
    xz: 1.1e-05
    yy: 0.004319
    yz: -3.6e-05
    zz: 0.000661

link4:
  origin:
    x: -0.0029006831074562967
    y: -0.03030575826634669
    z: 0.06339637422196209
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 0.6348534566833373
  inertia:
    xx: 0.000623
    xy: -1.0e-06
    xz: -1.9e-05
    yy: 0.000511
    yz: 3.8e-05
    zz: 0.000334

link5:
  origin:
    x: -0.003049665024221911
    y: 0.0008866902457326625
    z: 0.043079803024980934
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 0.6156588026168502
  inertia:
    xx: 0.000423
    xy: -8.0e-06
    xz: 6.0e-06
    yy: 0.000445
    yz: -6.0e-06
    zz: 0.000324

link6:
  origin:
    x: -0.037136587005447405
    y: 0.00033230528343419053
    z: -9.498374522309838e-05
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 0.475202773187987
  inertia:
    xx: 0.000143
    xy: 1e-06
    xz: 1e-06
    yy: 0.000157
    yz: 1e-06
    zz: 0.000159

link7:
  origin:
    x: 6.875510271106056e-05
    y: 0.01266175250761268
    z: 0.06951945409987448
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  mass: 0.4659771327380578
  inertia:
    xx: 0.000639
    xy: 1e-06
    xz: 1e-06
    yy: 0.000497
    yz: 8.9e-05
    zz: 0.000342
