# [SO-100 robot arm with ps4 controller]

# hid is used to read inputs from the PS4 controller.
# pip install hid
# Requires installing hidapi library: https://github.com/libusb/hidapi
# The PS4 controller should be connected via USB
# Bluetooth connection can partially work but may require some changes
# So far only tested on Mac and Ubuntu
# When running on ubuntu make sure that the user has access to the USB device (joystick)

_target_: lerobot.common.robot_devices.robots.manipulator.ManipulatorRobot
robot_type: so100
calibration_dir: .cache/calibration/so100

# `max_relative_target` limits the magnitude of the relative positional target vector for safety purposes.
# Set this to a positive scalar to have the same value for all motors, or a list that is the same length as
# the number of motors in your follower arms.
max_relative_target: null


# Add the controller
controller:
  _target_: lerobot.common.robot_devices.controllers.joysticks.PS4JoystickController
  motor_names:
    - shoulder_pan
    - shoulder_lift
    - elbow_flex
    - wrist_flex
    - wrist_roll
    - gripper
  initial_position: [90, 170, 170, 0, 0, 10]  # Configurable initial positions
  l1: 117.0  # Length of first lever in mm
  l2: 136.0  # Length of second lever in mm


follower_arms:
  main:
    _target_: lerobot.common.robot_devices.motors.feetech.FeetechMotorsBus
    port: /dev/tty.usbmodem585A0080971
    motors:
      # name: (index, model)
      shoulder_pan: [1, "sts3215"]
      shoulder_lift: [2, "sts3215"]
      elbow_flex: [3, "sts3215"]
      wrist_flex: [4, "sts3215"]
      wrist_roll: [5, "sts3215"]
      gripper: [6, "sts3215"]

cameras:
  laptop:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 0
    fps: 30
    width: 640
    height: 480
  phone:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 1
    fps: 30
    width: 640
    height: 480
