# @package _global_

fps: 50

env:
  name: aloha
  task: AlohaInsertion-v0
  state_dim: 14
  action_dim: 14
  fps: ${fps}
  episode_length: 400
  real_world: false
  gym:
    obs_type: pixels_agent_pos
    render_mode: rgb_array
