# @package _global_

fps: 5

env:
  name: my_custom_aloha
  task: place_baby
  state_dim: 2
  action_dim: 5
  fps: ${fps}
  episode_length: 400
  # gym:
  #   obs_type: pixels_agent_pos
  #   render_mode: rgb_array
