# @package _global_

eval_episodes: 50
eval_freq: 7500
save_freq: 75000
log_freq: 250
# TODO: same as simxarm, need to adjust
offline_steps: 25000
online_steps: 25000

fps: 10

dataset_id: pusht

env:
  name: pusht
  task: pusht
  from_pixels: True
  pixels_only: False
  image_size: 96
  action_repeat: 1
  episode_length: 300
  fps: ${fps}

policy:
  state_dim: 2
  action_dim: 2
